# Site
repository: haileyjohj/resume
# favicon: images/favicon.ico

# Personal info
name: 조혜진
title: Java 백엔드 엔지니어
email: hyejin.jo.0920@gmail.com
website: https://haileyjohj.github.io/

# Social links
# twitter_username: jojoldu
github_username:  haileyjohj
# dribbble_username: jekyll
# facebook_username: devbeginner
# flickr_username: jekyll
linkedin_username: hyejinjo0920
# pinterest_username: jekyll
# youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  자기소개 작성 중

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  외부활동 추가중
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
