# Site
repository: haileyjohj/resume
# favicon: images/favicon.ico

# Personal info
name: 조혜진
title: Java 백엔드 엔지니어
email: hyejin.jo.0920@gmail.com
website: https://haileyjohj.github.io/

# Social links
# twitter_username: jojoldu
github_username:  haileyjohj
# dribbble_username: jekyll
# facebook_username: devbeginner
# flickr_username: jekyll
linkedin_username: hyejinjo0920
# pinterest_username: jekyll
# youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/profile_pic.jpg
about_content: | # this will include new lines to allow paragraphs
  일본 도쿄 UT 테크놀로지 고탄다 본사에서 프론트, 백엔드 개발자로 2년간 일하며 파견사원 인사관리 사이트의 개발/배포/운용을 담당했습니다. 
  Java 언어를 기본으로 Spring, AngularJs, MySQL을 사용했습니다.

  초기 작업을 진행하다가 포기하고 나간 프로젝트를 디자인과 개발을 둘 다 할 수 있다는 이유로 신입 2명이 맡아 진행했습니다. 
  팀 상황이 열악했기 때문에 주도적으로 일을 찾아서 해결할 수밖에 없었던 좋은 기회이자 경험이었습니다. 
  DB 설계, 디자인, 개발, 서버 배포, 전체적인 스케줄 관리 등을 맡아 처리했습니다.

  실제로 사용할 영업사원들과 자주 회의를 갖고 요구 사항을 체크하고 피드백 받았습니다. 불편한 부분이 없는지 테스트하며 고쳐나갔습니다. 
  그 결과 각각 영업사원이 엑셀 수작업으로 관리하던 문서를 웹으로 옮겨 통합 관리할 수 있도록 체계를 만들었습니다. 
  현재는 3700명 이상의 파견사원을 등록하여 웹에서 관리하고 있습니다.

  상업 영화 현장에서 8년간 일하며 쌓은 팀 내 여러 가지 문제를 해결한 경험, 다른 팀과의 협업과 커뮤니케이션 등은 앞으로 조직 생활을 하면서도 큰 도움이 될 것이라 생각합니다. 
  또 디자이너로서의 센스를 바탕으로 사용자가 직관적으로 이용할 수 있는 시스템을 만들고 싶습니다. 
  사람들이 꼭 필요로하는 것, 생활을 좀 더 편리하게 만드는 데 도움이 되는 개발을 목표로 삼고 있습니다. 
  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  외부활동 추가중
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
